[package]
name = "erooster"
version = "0.1.0"
edition = "2021"
description = "An IMAP4v2 compatible imap server"
license = "AGPL-3.0-or-later"

[dependencies]
tokio = { version = "1", features = ["full"] }
nom = "7.1.0"
anyhow = "1.0.45"
tokio-util = { version = "0.7.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
rustls-pemfile = "0.3.0"
tokio-rustls ={ version = "0.23.1", features = ["tls12"] }
base64 = "0.13.0"
tracing = "0.1"
tracing-subscriber = "0.3"
simdutf8 = { version = "0.1.3" }
bytes = "1.1.0"
async-trait = "0.1.52"

[profile.release]
debug = true