[workspace]

members = [
    "crates/erooster",
    "crates/eroosterctl",
    "crates/erooster_core",
    "crates/erooster_imap",
    "crates/erooster_smtp",
    "crates/erooster_web",
]

[profile.dev.package.backtrace]
opt-level = 3