[package]
name = "erooster"
version = "0.1.0"
edition = "2021"
description = "An IMAP4v2 compatible mail server"
license = "Apache-2.0"
authors = ["MTRNord <mtrnord@nordgedanken.dev>"]
repository = "https://github.com/MTRNord/erooster/"
keywords = ["email","imap","smtp","simple","fast"]
categories = ["email", "network-programming"]

[dependencies]
tokio = { version = "1", features = ["full"] }
nom = "7.1.0"
color-eyre = "0.6"
tokio-util = { version = "0.7.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["net", "io-util"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
rustls-pemfile = "1.0.0"
tokio-rustls ={ version = "0.23.1", features = ["tls12"] }
base64 = "0.13.0"
tracing = "0.1"
tracing-subscriber = "0.3"
simdutf8 = { version = "0.1.3" }
bytes = "1.1.0"
async-trait = "0.1.52"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = { version = "3.1.6", features = ["derive", "color", "suggestions","env"] }
notify = "5.0.0-pre.13"
const_format = "0.2.22"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls"] }

[dependencies.maildir]
version = "0.6.1"
#git = "https://github.com/soywod/maildir"
#rev = "179625c3cc15212fb26eca5b819f7fe0d6f802e1"

[features]
default = ["postgres"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

#[profile.release]
#debug = true

[dev-dependencies]
criterion = {version = "0.3", features = ["async_tokio"]}

[[bench]]
name = "smtp_bench"
harness = false

[profile.dev.package.backtrace]
opt-level = 3