[package]
name = "erooster"
version = "0.1.0"
edition = "2021"
description = "An IMAP4v2 compatible mail server"
license = "Apache-2.0"
authors = ["MTRNord <mtrnord@nordgedanken.dev>"]
repository = "https://github.com/MTRNord/erooster/"
keywords = ["email","imap","smtp","simple","fast"]
categories = ["email", "network-programming"]

[[bin]]
name = "erooster"
path = "src/cmds/erooster.rs"
bench = false

[[bin]]
name = "eroosterctl"
path = "src/cmds/eroosterctl.rs"
bench = false

[lib]
name = "erooster"
path = "src/lib.rs"
bench = false

[dependencies]
tokio = { version = "1", features = ["full"] }
nom = "7.1.0"
color-eyre = "0.6"
tokio-util = { version = "0.7.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["net", "io-util"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
rustls-pemfile = "1.0.0"
tokio-rustls ={ version = "0.23.1", features = ["tls12"] }
base64 = "0.13.0"
tracing = "0.1"
tracing-subscriber = "0.3"
simdutf8 = { version = "0.1.3" }
bytes = "1.1.0"
async-trait = "0.1.52"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = { version = "3.1.6", features = ["derive", "color", "suggestions","env"] }
notify = "5.0.0-pre.13"
const_format = "0.2.22"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls"] }
argon2 = { version = "0.4", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }
sqlxmq = { version = "0.3", default-features = false, features = [ "runtime-tokio-rustls"] }
owo-colors = "3"
rpassword = "6.0.1"
indicatif = "0.16.2"
clearscreen = "1.0.9"
rustls = "0.20.6"
cfg-if = "1.0.0"
trust-dns-resolver = "0.21.2"
mailparse = "0.13.8"
rustls-native-certs = "0.6.2"

[build-dependencies]
clap_mangen = "0.1"
clap = { version = "3.1.6", features = ["derive", "color", "suggestions","env"] }

[dependencies.maildir]
version = "0.6.1"
#git = "https://github.com/soywod/maildir"
#rev = "179625c3cc15212fb26eca5b819f7fe0d6f802e1"
optional = true

[features]
default = ["maildir"]
maildir = ["dep:maildir"]

#[profile.release]
#debug = true

[dev-dependencies]
criterion = {version = "0.3", features = ["async_tokio"]}
enum-iterator = "0.8.1"
enum-display-derive = "0.1.1"
convert_case = "0.5.0"

[[bench]]
name = "smtp_bench"
harness = false

[profile.dev.package.backtrace]
opt-level = 3