tls:
  key_path: "./certs/key.pem"
  cert_path: "./certs/cert.pem"
mail:
  maildir_folders: "./maildir"
  hostname: "localhost"
database:
  postgres_url: ""
webserver:
  ip: "127.0.0.1"
  port: "80"
  tls: false
sentry: false
