[package]
name = "eroosterctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erooster_core = {version = "0.1.0", path="../erooster_core"}
clearscreen = "1.0"
clap = { version = "3.1", features = ["derive", "color", "suggestions","env"] }
color-eyre = "0.6"
indicatif = "0.16"
opentelemetry = { version = "0.17", features = ["metrics", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"], optional = true }
owo-colors = "3"
rpassword = "6.0"
sentry = { version = "0.26", default-features = false, features = ["tracing", "backtrace", "contexts", "panic", "ureq"]}
sys-info = "0.9"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = {version = "0.3", features=["env-filter"]}

[features]
default = []
jaeger = ["dep:opentelemetry-jaeger"]

[build-dependencies]
vergen = "7"
