on: [push]
name: Benchmark
jobs:
  runBenchmark:
    name: Run Benchmark
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: erooster
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - run: rustup default nightly
      - uses: Swatinem/rust-cache@v1
      - name: Setup Config
        run: |
          echo 'tls:' > config.yml
          echo '  key_path: ""' >> config.yml
          echo '  cert_path: ""' >> config.yml
          echo 'mail:' >> config.yml
          echo '  maildir_folders: "./maildir"' >> config.yml
          echo '  hostname: "localhost"' >> config.yml
          echo 'database:' >> config.yml
          echo '  postgres_url: "postgres://postgres:postgres@localhost/erooster"' >> config.yml
      - uses: boa-dev/criterion-compare-action@v3.0.0
        with:
          branchName: ${{ github.ref_name }}
          token: ${{ github.token }}
