on: [pull_request, push]
name: Benchmark
jobs:
  runBenchmark:
    name: Run Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup default nightly
      - uses: boa-dev/criterion-compare-action@v3.0.0
        with:
          branchName: ${{ github.base_ref }}
          token: ${{ github.token }}
