on: [pull_request, push]
name: Benchmark
jobs:
  runBenchmark:
    name: Run Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: boa-dev/criterion-compare-action@v3.0.0
        with:
          branchName: ${{ github.base_ref }}
          # Optional. Default is `${{ github.token }}`.
          # token: ${{ secrets.GITHUB_TOKEN }}
